// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://chclxuqsmzzkqwinwxxg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNoY2x4dXFzbXp6a3F3aW53eHhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMzYxMDYsImV4cCI6MjA2NTkxMjEwNn0.a2pjjyto1IBdAGGfe2MBjP39VYQcP4x35mS8W9lkMdY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);